#!/usr/bin/env bash
T=$(dirname $0)
if [ ${T:0:1} != "/" ]; then 
   T=$PWD/$T
fi

dollar="$"
function assign() {
	 if eval [ X"$dollar$1" == X ]; then
	    if [ -d "$2" ]; then
	       eval export $1="$2"
	    else
	       eval export $1="$3"
	    fi
	 fi
}

export LD_LIBRARY_PATH=$T/viewer/bin
export VIMAGE=eog
export VEDITOR=gedit
assign "VMODELS"   ./models   $T/models
assign "VTEXTURES" ./Textures $T/Textures
assign "VTESTS"    ./tests    $T/tests
export LC_NUMERIC="C"
export VPLUGINS="libdraw-vbo-ext.so;libshaderloader.so;libnavigatedefault.so"

VGLRUN=""
VGLARGS=""
if [ X$1 == 'X-vgl' ]; then
    shift
    if [ -x /usr/bin/vglrun ]; then
	VGLRUN="/usr/bin/vglrun"
	VGLARGS=" +sync +sp "
    fi
fi

echo "Environment"
echo "VMODELS = " $VMODELS 
echo "VTEXTURES = " $VTEXTURES
echo "VTESTS = " $VTESTS
echo -n "about to execute: "
echo ${VGLRUN} ${VGLARGS} $T/viewer/bin/viewerd $@
${VGLRUN} ${VGLARGS} $T/viewer/bin/viewerd $@


